services:
  relay:
    container_name: haven-relay
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./haven:/app/haven"
    ports:
      - "3355"
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"

  tor:
    image: lncm/tor:0.4.7.9@sha256:86c2fe9d9099e6376798979110b8b9a3ee5d8adec27289ac4a5ee892514ffe92
    container_name: haven-tor
    depends_on:
      - relay
    volumes:
      - ./tor/torrc:/etc/tor/torrc
      - ./tor/data:/var/lib/tor
    restart: on-failure
    stop_grace_period: 10m30s
